{"name": "test_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 10 == 20", "trace": "def test_1():\n        x = 10\n        y = 20\n>       assert x == y\nE       assert 10 == 20\n\nTestCases\\test_1.py:5: AssertionError"}, "start": 1706465355624, "stop": 1706465355625, "uuid": "e80564bd-5e5e-421e-aae2-b7491a3f8643", "historyId": "2180d24d0c15116f8b0ac778ec4fe1a7", "testCaseId": "2180d24d0c15116f8b0ac778ec4fe1a7", "fullName": "TestCases.test_1#test_1", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_1"}, {"name": "host", "value": "LAPTOP-DD031UVH"}, {"name": "thread", "value": "16476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_1"}]}